### ISSUE TITLE
Wrong base url in "upload file" endpoint

### ISSUE THREAD

**Issue by codal-mdesai** [box/box-openapi#417]
### Description of the issue

Incorrect base url mapped for CURL example For Upload File and all upload endpoints where base url should be "https://upload.box.com" instead of "https://api.box.com"

### Current content

curl -i -X POST "**https://api.box.com/**2.0/files/content" \
     -H "authorization: Bearer <ACCESS_TOKEN>" \
     -H "content-type: multipart/form-data" \
     -F attributes='{"name":"Contract.pdf", "parent":{"id":"11446498"}}' \
     -F file=@<FILE_NAME>

### Expected content

curl -i -X POST "**https://upload.box.com/api/**2.0/files/content" \
     -H "authorization: Bearer <ACCESS_TOKEN>" \
     -H "content-type: multipart/form-data" \
     -F attributes='{"name":"Contract.pdf", "parent":{"id":"11446498"}}' \
     -F file=@<FILE_NAME>

### Link to the documentation page

https://developer.box.com/reference/post-files-content/

**Comment by bszwarc** [comment]
Thank you for pointing this one out - we have fixed it.

**Comment by codal-mdesai** [comment]
![image](https://github.com/box/box-openapi/assets/46340995/eb592fef-75b1-415d-9e3f-4c48db474a14)
unfortunately I am still seeing this issue

**Comment by bszwarc** [comment]
It should be fine now: https://developer.box.com/reference/post-files-content/ - we were waiting for the build to finish :D

**Comment by antusus** [comment]
Hello,
this issue is fixed now.
Thank you for reporting that.
